name: Build and Install OpenVINO

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            git \
            wget \
            python3-dev \
            python3-pip \
            libopencv-dev \
            lsb-release \
            gnupg

      - name: Install OpenVINO Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libusb-1.0-0 \
            libudev-dev \
            libnuma-dev

      - name: Download and Install OpenVINO (with correct download link)
        run: |
          wget https://registrationcenter-download.intel.com/akdlm/irc_nas/17437/l_openvino_2021.4.2.643_offline.tgz
          tar -xvf l_openvino_2021.4.2.643_offline.tgz
          cd l_openvino_2021.4.2.643
          sudo ./install_GUI.sh --silent

      - name: Source OpenVINO environment variables
        run: |
          source /opt/intel/openvino_2021.4.2.643/env/vars.sh
          
      - name: Install Python bindings for OpenVINO
        run: |
          pip install --upgrade pip
          pip install openvino

      - name: Verify OpenVINO installation
        run: |
          source /opt/intel/openvino_2021.4.2.643/env/vars.sh
          python -c "import openvino"
          
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Build the project
        run: |
          mkdir -p build
          cd build
          cmake ..
          make

      - name: Run tests
        run: |
          cd build
          ./your_test_executable

