name: Build and Export Library on Windows

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # التحقق من الشيفرة
      - name: Checkout Repository
        uses: actions/checkout@v3

      # إعداد بيئة OpenVINO
      - name: Install OpenVINO
        run: |
          curl -o openvino.exe https://registrationcenter-download.intel.com/akdlm/irc_nas/17770/l_openvino_toolkit_p_2021.4.752.exe
          start /wait openvino.exe --silent --installpath "C:\Program Files (x86)\Intel\OpenVINO"
          setx INTEL_OPENVINO_DIR "C:\Program Files (x86)\Intel\OpenVINO"
          setx PATH "%PATH%;C:\Program Files (x86)\Intel\OpenVINO\bin"
          "C:\Program Files (x86)\Intel\OpenVINO\bin\setupvars.bat"

      # تثبيت أدوات البناء الأساسية
      - name: Install Build Tools
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y
          choco install visualstudio2019buildtools -y
          choco install opencv -y
          refreshenv

      # إعداد مجلد البناء
      - name: Create Build Directory
        run: mkdir build

      # بناء المشروع باستخدام CMake
      - name: Build Project
        run: |
          cd build
          cmake .. -G "Visual Studio 16 2019" -A x64 -DOpenVINO_DIR="C:\Program Files (x86)\Intel\OpenVINO\runtime\cmake"
          cmake --build . --config Release

      # رفع المكتبة الناتجة
      - name: Upload Built Library
        uses: actions/upload-artifact@v3
        with:
          name: built_library
          path: build/Release/trained_model.dll
