name: Build and Export Library (Windows)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # التحقق من الشيفرة
      - name: Checkout Repository
        uses: actions/checkout@v3

      # تثبيت متطلبات البناء على Windows
      - name: Install Build Tools and Dependencies
        run: |
          choco install -y visualstudio2022buildtools visualstudio2022-workload-vctools cmake python
          refreshenv
          pip install --upgrade pip
          pip install openvino

      # تحميل وتثبيت OpenVINO على Windows
      - name: Install OpenVINO
        run: |
          curl -L -o openvino.zip https://storage.openvinotoolkit.org/repositories/openvino/2021.4/l_openvino_toolkit_runtime_windows_2021.4.752.zip
          tar -xf openvino.zip
          cd l_openvino_toolkit_runtime_windows_2021.4.752
          setupvars.bat
          call install_dependencies.bat

      # إعداد مجلد البناء
      - name: Create Build Directory
        run: mkdir build

      # بناء المشروع باستخدام CMake
      - name: Build Project
        run: |
          cd build
          cmake .. -G "Visual Studio 17 2022" -DOpenVINO_DIR="C:/Program Files (x86)/IntelSWTools/openvino_2021.4.752/deployment_tools/cmake"
          cmake --build . --config Release

      # رفع المكتبة
      - name: Upload Built Library
        uses: actions/upload-artifact@v3
        with:
          name: built_library
          path: build/Release/trained_model.lib # أو اسم الملف الناتج
